#include <windows.h>
#include <winternl.h>

#define TEB_PPEB_OFFSET64 0x60

VOID FindKernel32(VOID);
PVOID LocateFunction(LPCSTR, LPCSTR);
BOOL StrCmp(LPSTR, LPSTR);
BOOL WStrCmp(LPWSTR, LPWSTR);


typedef HMODULE LOAD_LIBRARY_A(LPCSTR);
typedef PVOID GET_PROC_ADDRESS(HMODULE, LPCSTR);

typedef LOAD_LIBRARY_A *PLOAD_LIBRARY_A;
typedef GET_PROC_ADDRESS *PGET_PROC_ADDRESS;
